version: '3'

services:
  web:
    build: ../../
    container_name: de-cguard_backend
    networks:
      - default
      - docker
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.web-decguardbackend-stripprefix.stripprefix.prefixes=/api/v1
      - traefik.http.middlewares.web-decguardbackend-headers.headers.accessControlAllowOrigin=*
      - traefik.http.routers.web-decguardbackend.entrypoints=websecure
      - traefik.http.routers.web-decguardbackend.middlewares=de-decguardbackend-stripprefix,web-decguardbackend-headers
      - traefik.http.routers.web-decguardbackend.rule=Host(`cguard.de`, `www.cguard.de`) && PathPrefix(`/api/v1/`)
      - traefik.http.routers.web-decguardbackend.tls.certresolver=le
      - traefik.http.services.backend-decguardbackend.loadbalancer.server.port=3000
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:latest
    container_name: de-cguard_backend_db
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=WriZxnxK2d756q29NA2WGrR3
      - MYSQL_DATABASE=wvv

networks:
  default:
  docker:
    external:
      name: docker
